object_detection:
    minArea: 1000
    maxArea: 6000
    rectPadding: 5
    heightCorrection: 10
    crop:
        wMin: -1
        wMax: 1
        hMin: 0.01
        hMax: 0.1
        dMin: 0.1
        dMax: 1.5
    voxel:
        leafsize: 0.005
    hsv0:
        color: purple
        hmin: 113
        hmax: 166
        smin: 70
        smax: 136
        vmin: 121
        vmax: 220
        updiffh: 0
        updiffs: 0
        updiffv: 0
        lowdiffh: 0
        lowdiffs: 0
        lowdiffv: 0
    hsv1:
        color: blue
        hmin: 60
        hmax: 117
        smin: 49
        smax: 255
        vmin: 0
        vmax: 255
        updiffh: 87.89
        updiffs: 88.39
        updiffv: 84.82
        lowdiffh: 71.76
        lowdiffs: 88.94
        lowdiffv: 57.14
    hsv2:
        color: green
        hmin: 24
        hmax: 70
        smin: 69
        smax: 255
        vmin: 48
        vmax: 255
        updiffh: 234.4
        updiffs: 193.5
        updiffv: 197.8
        lowdiffh: 107.4
        lowdiffs: 63.5
        lowdiffv: 82.3
    hsv3:
        color: yellow
        hmin: 12
        hmax: 36
        smin: 106
        smax: 255
        vmin: 151
        vmax: 255
        updiffh: 172.6
        updiffs: 129.8
        updiffv: 94.5
        lowdiffh: 105.1
        lowdiffs: 25.8
        lowdiffv: 212.7
    hsv4:
        color: red
        hmin: 150
        hmax: 180
        smin: 118
        smax: 255
        vmin: 0
        vmax: 255
        updiffh: 180
        updiffs: 152.5
        updiffv: 138.9
        lowdiffh: 192.4
        lowdiffs: 51.7
        lowdiffv: 124.5
    hsv5:
        color: orange
        hmin: 0
        hmax: 55
        smin: 157
        smax: 255
        vmin: 161
        vmax: 255
        updiffh: 0
        updiffs: 0
        updiffv: 0
        lowdiffh: 0
        lowdiffs: 0
        lowdiffv: 0

