object_detection:
    crop:
        wMin: -1
        wMax: 1
        hMin: 0.01
        hMax: 0.1
        dMin: 0.1
        dMax: 3
    voxel:
        leafsize: 0.005
    hsv1:
        hmin: 0
        hmax: 180
        smin: 0
        smax: 180
        vmin: 56
        vmax: 255
    hsv2:
        hmin: 43
        hmax: 180
        smin: 65
        smax: 255
        vmin: 0
        vmax: 255
