object_detection:
    crop:
        widthMin: -1
        widthMax: 1
        heightMin: 0
        heightMax: 1
        depthMin: 0.1
        depthMax: 3
    voxel:
        leafsize: 0.005
    hsv1:
        hmin: 0
        hmax: 180
        smin: 0
        smax: 180
        vmin: 56
        vmax: 255
    hsv2:
        hmin: 43
        hmax: 180
        smin: 65
        smax: 255
        vmin: 0
        vmax: 255
